#!/bin/sh

case "$1 $2" in
  "--version ")
    printf '%s\n' 'vTEST_ONLY'
    ;;
  "profile get")
    if [ "${VIDMUSE_TEST_UNAUTH:-0}" = "1" ]; then
      printf '%s\n' 'TEST_ONLY_AUTH_REQUIRED' >&2
      exit 3
    fi
    printf '%s\n' '{"id":"TEST_ONLY_PROFILE"}'
    ;;
  "plan get")
    printf '%s\n' '{"plan":"TEST_ONLY_PLAN"}'
    ;;
  "model list")
    printf '%s\n' '{"data":[{"name":"TEST_ONLY_MODEL"}]}'
    ;;
  *)
    printf '%s\n' 'unsupported test command' >&2
    exit 2
    ;;
esac
